### ISSUE TITLE
result.csv中的labels为什么不是distance distribution value？

### ISSUE THREAD

**Issue by Psygoal** [ArthurWillYu/CNN-RNN-Raman#1]
原文中不是提到"we changed the label of the model training set so that it no longer had the traditional integer value but contained
the distance distribution value"吗？此处labels本应该是“distance distribution value”吗？并且原文提到"We chose the first strain as the control strain and set the label value to 1"但csv文件中为0？

**Comment by ArthurWillYu** [comment]
> 原文中不是提到"we changed the label of the model training set so that it no longer had the traditional integer value but contained
> the distance distribution value"吗？此处labels本应该是“distance distribution value”吗？并且原文提到"We chose the first strain as the control strain and set the label value to 1"但csv文件中为0？

label在运行文件中进行的更改，请详细查看后再进行询问，谢谢！
